class DestinyDefinition
  
  DEFINITIONS = {
    'EnemyRace' => 'DestinyEnemyRaceDefinition', 
    'NodeStepSummary' => 'DestinyNodeStepSummaryDefinition', 
    'ArtDyeChannel' => 'DestinyArtDyeChannelDefinition', 
    'ArtDyeReference' => 'DestinyArtDyeReferenceDefinition', 
    'Place' => 'DestinyPlaceDefinition', 
    'Activity' => 'DestinyActivityDefinition', 
    'ActivityType' => 'DestinyActivityTypeDefinition', 
    'xClass' => 'DestinyClassDefinition', 
    'Gender' => 'DestinyGenderDefinition', 
    'InventoryBucket' => 'DestinyInventoryBucketDefinition', 
    'Race' => 'DestinyRaceDefinition', 
    'TalentGrid' => 'DestinyTalentGridDefinition', 
    'Unlock' => 'DestinyUnlockDefinition', 
    'MaterialRequirementSet' => 'DestinyMaterialRequirementSetDefinition', 
    'SandboxPerk' => 'DestinySandboxPerkDefinition', 
    'StatGroup' => 'DestinyStatGroupDefinition', 
    'ProgressionMapping' => 'DestinyProgressionMappingDefinition', 
    'Faction' => 'DestinyFactionDefinition', 
    'VendorGroup' => 'DestinyVendorGroupDefinition', 
    'RewardSource' => 'DestinyRewardSourceDefinition',
    'UnlockValue' => 'DestinyUnlockValueDefinition', 
    'RewardMapping' => 'DestinyRewardMappingDefinition', 
    'RewardSheet' => 'DestinyRewardSheetDefinition', 
    'ItemCategory' => 'DestinyItemCategoryDefinition', 
    'DamageType' => 'DestinyDamageTypeDefinition', 
    'ActivityMode' => 'DestinyActivityModeDefinition', 
    'MedalTier' => 'DestinyMedalTierDefinition', 
    'Achievement' => 'DestinyAchievementDefinition', 
    'ActivityGraph' => 'DestinyActivityGraphDefinition', 
    'ActivityInteractable' => 'DestinyActivityInteractableDefinition', 
    'Collectible' => 'DestinyCollectibleDefinition', 
    'Stat' => 'DestinyStatDefinition', 
    'ItemTierType' => 'DestinyItemTierTypeDefinition', 
    'PlatformBucketMapping' => 'DestinyPlatformBucketMappingDefinition', 
    'PresentationNode' => 'DestinyPresentationNodeDefinition', 
    'Record' => 'DestinyRecordDefinition', 
    'Bond' => 'DestinyBondDefinition', 
    'CharacterCustomizationCategory' => 'DestinyCharacterCustomizationCategoryDefinition', 
    'CharacterCustomizationOption' => 'DestinyCharacterCustomizationOptionDefinition', 
    'Destination' => 'DestinyDestinationDefinition', 
    'EquipmentSlot' => 'DestinyEquipmentSlotDefinition', 
    'InventoryItem' => 'DestinyInventoryItemDefinition', 
    'Location' => 'DestinyLocationDefinition', 
    'Lore' => 'DestinyLoreDefinition', 
    'Objective' => 'DestinyObjectiveDefinition', 
    'Progression' => 'DestinyProgressionDefinition', 
    'ProgressionLevelRequirement' => 'DestinyProgressionLevelRequirementDefinition', 
    'RewardAdjusterProgressionMap' => 'DestinyRewardAdjusterProgressionMapDefinition', 
    'RewardItemList' => 'DestinyRewardItemListDefinition', 
    'SackRewardItemList' => 'DestinySackRewardItemListDefinition', 
    'SandboxPattern' => 'DestinySandboxPatternDefinition', 
    'Season' => 'DestinySeasonDefinition', 
    'SocketCategory' => 'DestinySocketCategoryDefinition', 
    'SocketType' => 'DestinySocketTypeDefinition', 
    'UnlockCountMapping' => 'DestinyUnlockCountMappingDefinition', 
    'UnlockEvent' => 'DestinyUnlockEventDefinition', 
    'UnlockExpressionMapping' => 'DestinyUnlockExpressionMappingDefinition', 
    'Vendor' => 'DestinyVendorDefinition', 
    'RewardAdjusterPointer' => 'DestinyRewardAdjusterPointerDefinition', 
    'Milestone' => 'DestinyMilestoneDefinition', 
    'ActivityModifier' => 'DestinyActivityModifierDefinition', 
    'ReportReasonCategory' => 'DestinyReportReasonCategoryDefinition', 
    'PlugSet' => 'DestinyPlugSetDefinition', 
    'Checklist' => 'DestinyChecklistDefinition'
  }

  self::DEFINITIONS.each do |k,v|
    define_singleton_method k.camelize(:lower) do
      v
    end
  end
end